### ISSUE TITLE
nodemon error

### ISSUE THREAD

**Issue by USERARSSASion** [docker/labs#236] opened 2017-04-15 12:42 UTC
Attaching to nodedocker_web_1
web_1  |   Usage: nodemon [nodemon options] [script.js] [args]
web_1  | 
web_1  |   See "nodemon --help" for more.
web_1  | 
nodedocker_web_1 exited with code 0
[root@localhost nodeDocker]# nodemon --help

`  1 version: "2" 
  2      
  3 services: 
  4     web: 
  5         build: . 
  6         command: nodemon --debug=5858 
  7         volumes: 
  8              - .:/code 
  9         ports: 
 10              - "8000:8000" 
 11              - "5858:5858"

`

**Comment by ManoMarks** [comment] 2017-04-25 23:09
I'm unable to reproduce this error. Please provide the following information:

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**


**Description**



**Steps to reproduce the issue, if relevant:**
1.
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by ManoMarks** [comment] 2017-05-01 19:41
@USERARSSASion I'm closing this as we have no more information incoming. Re-open if you can provide more info that allows us to reproduce it.

**Closed by ManoMarks** 2017-05-01 19:41 UTC
